steps added.

diff --git a/.github/workflows/build_and_test_prod.yml b/.github/workflows/build_and_test_prod.yml
--- a/.github/workflows/build_and_test_prod.yml
+++ b/.github/workflows/build_and_test_prod.yml
@@ -19,38 +19,29 @@ jobs:
     permissions:
       checks: write
     steps:
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0 #fetch-depth is needed for GitVersion
-
-      - name: Setup .NET
-        #Build/pack the project
-        uses: actions/setup-dotnet@v4
-        with:
-          dotnet-version: 9.0.x
-      # - name: Verify solution Path
-      #   run: ls -la $SLN_FILE
-
-      - name: Restore dependencies
-        run: dotnet restore
-      - name: Build
-        run: dotnet build --no-restore
-      # - name: Display secrets
-      #   run: |
-      #     echo clientId: $clientId
-      #     echo clientSecret: $clientSecret
-      - name: Test
-        run: dotnet test --verbosity normal --logger "trx;LogFileName=test-results.trx" --results-directory "TestResults"
-      - name: Test Report
-        uses: dorny/test-reporter@v1
-        if: success() || failure() # run this step even if previous step failed
-        with:
-          name: Test Report # Name of the check run which will be created
-          reporter: dotnet-trx # Format of test results
-          list-tests: "all"
-          fail-on-error: "false"
-          #artifact: test-results
-          path: TestResults/test-results.trx # Path to test results (inside artifact .zip)
+    - uses: actions/checkout@v4
+    - name: Setup .NET
+      uses: actions/setup-dotnet@v4
+      with:
+        dotnet-version: 9.0.x
+    # - name: Verify solution Path
+    #   run: ls -la $SLN_FILE
+    - name: Restore dependencies
+      run: dotnet restore
+    - name: Build
+      run: dotnet build --no-restore
+    - name: Test
+      run: dotnet test --verbosity normal --logger "trx;LogFileName=test-results.trx" --results-directory "TestResults"
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure() # run this step even if previous step failed
+      with:
+        name: Test Report # Name of the check run which will be created
+        reporter: dotnet-trx # Format of test results
+        list-tests: "all"
+        fail-on-error: "false"
+        #artifact: test-results
+        path: TestResults/test-results.trx # Path to test results (inside artifact .zip)
   # TestReport:
   #   steps:
   #     - name: Test
